import { StyleSheet } from "react-native";

export default StyleSheet.create({
    party: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '96%',
        margin: 'auto',
        marginTop:0,
        marginBottom: 0,
        zIndex: 0,
      },
      tabs: {
        display: 'flex',
        justifyContent: 'space-evenly',
        width: '80%',
        margin: 'auto',
        marginBottom: 20,
        marginTop: 0,
      },
      tab: {
        padding: 10,
        paddingHorizontal: 20,
        cursor: 'pointer',
        backgroundColor: 'transparent',
        fontSize: 20,
        position: 'relative',
      },
      activeTab: {
        backgroundColor: 'transparent',
      },
      tabIndicator: {
        position: 'absolute',
        bottom: -3,
        left: -20,
        width: '160%',
        height: 2,
        backgroundColor: 'black',
        borderRadius: 10,
      },
      tabContent: {
        padding: 20,
        height: '66vh',
        width: '100%',
      },
      finishOverlay: {
        position: 'fixed',
        bottom: '-100%',
        left: 0,
        width: '100%',
        height: '100%',
        zIndex: 600,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
      },
      finishOverlayShow: {
        bottom: 0,
        transition: 'bottom 3.5s ease-in-out',
      },
      fadeIn: {
        position: 'fixed',
        top: '50%',
        left: '50%',
        transform: [{ translateX: '-50%' }, { translateY: '-50%' }],
        opacity: 0,
        transition: 'opacity 1s ease-in-out',
        zIndex: 700,
        textAlign: 'center',
        color: 'black',
        fontSize: 24,
        fontFamily: 'raleway',
        fontWeight: 'bold',
      },
});